spring:
  application:
    name: contact-list

  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/contacts_db}
    username: ${DB_USER:postgres}
    password: ${DB_USER_PSWD:postgres}
    driverClassName: org.postgresql.Driver
    hikari:
      schema: contacts_schema
logging:
  level:
    root: INFO