spring:
  application:
    name: contact-list

  datasource:
    url: jdbc:postgresql://localhost:5432/contacts_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      schema: contacts_schema
logging:
  level:
    root: DEBUG